version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '${PG_PASS}'
    ports:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    image: ninja-store:alpine01
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - SECRET_KEY_BASE="${KEY_BASE}"
      - RAILS_ENV=production
      - 'DATABASE_URL=postgres://postgres:${PG_PASS}@db:5432'
      - RAILS_SERVE_STATIC_FILES=true
      - JWT_SECRET
      - ADMIN_EMAIL
      - MAILER_SENDER
      - MAILER_PASSWORD
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY
      - END_POINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - '3000:3000'
    #volumes:
    # - rails-data:/home/railsApp/data
    depends_on:
      - db
volumes:
  postgres-data:
  #rails-data:
