version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '${PG_PASS}'
    ports:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      #- SECRET_KEY_BASE="${KEY_BASE}"
      - 'DATABASE_URL=postgres://postgres:${PG_PASS}@db:5432'
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  postgres-data:
