version: '3'
volumes:
  postgres-data:
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: oktonokto1
    ports:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - SECRET_KEY_BASE="${KEY_BASE}"
      - DATABASE_URL="${PSQL}"
      - RAILS_SERVE_STATIC_FILES=true
    # volumes:
    #   - .:/project #only in development
    ports:
      - '3000:3000'
    depends_on:
      - db
    # restart: always
